// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbnjzhetztivbtjvyayd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxibmp6aGV0enRpdmJ0anZ5YXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDE2MTYsImV4cCI6MjA2NDY3NzYxNn0.i2pfXRp2t4zKVxO0_AykOcgAHcwgJQPvOvsp0gvpYpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);